#!/usr/bin/bash

cd hanzi-frontend
npm run build

cd ..
git add .
git status --porcelain

if git diff --cached --quiet; then
    echo "No changes to commit."
else
    git commit -m "$commit_message"
    
    if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{u})" ]; then
        git push
    else
        echo "No changes to push."
    fi
fi
