"""add user_custom-definition

Revision ID: 0e8a9843eeca
Revises: d14093709a33
Create Date: 2025-10-22 22:53:12.704856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8a9843eeca'
down_revision = 'd14093709a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_custom_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hanzi', sa.String(length=512), nullable=False),
    sa.Column('pinyin', sa.String(length=256), nullable=True),
    sa.Column('english', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hanzi', name='uq_user_custom_definition_user_hanzi')
    )
    with op.batch_alter_table('user_custom_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_custom_definition_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_custom_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_custom_definition_user_id'))

    op.drop_table('user_custom_definition')
    # ### end Alembic commands ###
