"""add fsrs_review_log

Revision ID: 645e4415f4b8
Revises: 998223d88e06
Create Date: 2026-05-04 13:40:16.172032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645e4415f4b8'
down_revision = '998223d88e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsrs_review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.Column('state_after', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fsrs_review_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fsrs_review_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_fsrs_review_log_user_reviewed_at', ['user_id', 'reviewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fsrs_review_log', schema=None) as batch_op:
        batch_op.drop_index('ix_fsrs_review_log_user_reviewed_at')
        batch_op.drop_index(batch_op.f('ix_fsrs_review_log_user_id'))

    op.drop_table('fsrs_review_log')
    # ### end Alembic commands ###
