"""add rating tallies and time_ms to fsrs_daily_stats

Revision ID: 998223d88e06
Revises: a4adfa5bf416
Create Date: 2026-05-04 00:23:04.414453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998223d88e06'
down_revision = 'a4adfa5bf416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fsrs_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('again_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('hard_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('good_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('easy_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('time_ms', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fsrs_daily_stats', schema=None) as batch_op:
        batch_op.drop_column('time_ms')
        batch_op.drop_column('easy_count')
        batch_op.drop_column('good_count')
        batch_op.drop_column('hard_count')
        batch_op.drop_column('again_count')

    # ### end Alembic commands ###
