"""add fsrs review tables

Revision ID: a4adfa5bf416
Revises: 0e8a9843eeca
Create Date: 2026-05-01 22:42:27.467348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4adfa5bf416'
down_revision = '0e8a9843eeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsrs_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('new_introduced', sa.Integer(), nullable=False),
    sa.Column('reviews_done', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_fsrs_daily_stats_user_date')
    )
    with op.batch_alter_table('fsrs_daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fsrs_daily_stats_user_id'), ['user_id'], unique=False)

    op.create_table('fsrs_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_fsrs_review_user_word')
    )
    with op.batch_alter_table('fsrs_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fsrs_review_due'), ['due'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_review_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_review_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fsrs_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fsrs_review_word'))
        batch_op.drop_index(batch_op.f('ix_fsrs_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_fsrs_review_due'))

    op.drop_table('fsrs_review')
    with op.batch_alter_table('fsrs_daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fsrs_daily_stats_user_id'))

    op.drop_table('fsrs_daily_stats')
    # ### end Alembic commands ###
