"""add review_duration to fsrs_review_log

Revision ID: cf9d81fa5734
Revises: 645e4415f4b8
Create Date: 2026-05-04 14:04:52.117033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9d81fa5734'
down_revision = '645e4415f4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fsrs_review_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fsrs_review_log', schema=None) as batch_op:
        batch_op.drop_column('review_duration')

    # ### end Alembic commands ###
