"""updated stroke data from json to blob

Revision ID: 065bdb29493d
Revises: 4ef7073f7920
Create Date: 2025-03-07 16:27:14.757526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '065bdb29493d'
down_revision = '4ef7073f7920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke_data', schema=None) as batch_op:
        batch_op.drop_column('strokes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strokes', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
