"""Remove timestamp from wordentry

Revision ID: 255a31ebba2b
Revises: d7f75c74ac68
Create Date: 2025-03-09 02:33:51.846851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255a31ebba2b'
down_revision = 'd7f75c74ac68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_entry', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
