"""Remove positioner and other stuff from StrokeData

Revision ID: 4ef7073f7920
Revises: a488d80d1a19
Create Date: 2025-03-07 16:08:33.718739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4ef7073f7920'
down_revision = 'a488d80d1a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke_data', schema=None) as batch_op:
        batch_op.drop_column('stroke_count')
        batch_op.drop_column('positioner')
        batch_op.drop_column('mistakes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mistakes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('positioner', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('stroke_count', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
