"""Add character lists models

Revision ID: a608012aba0e
Revises: cf3fad85266f
Create Date: 2025-03-08 02:27:57.035770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a608012aba0e'
down_revision = 'cf3fad85266f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=10), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['word_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character_entry')
    op.drop_table('character_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character', sa.VARCHAR(length=1), nullable=False),
    sa.Column('list_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['character_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('word_entry')
    op.drop_table('word_list')
    # ### end Alembic commands ###
