"""Add timestamp to wordentry

Revision ID: d7f75c74ac68
Revises: a608012aba0e
Create Date: 2025-03-08 23:00:21.173427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f75c74ac68'
down_revision = 'a608012aba0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_entry', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
