"""updated stroke data

Revision ID: e1ad226ce58e
Revises: 39c22cef0b5d
Create Date: 2025-03-07 17:41:55.339834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ad226ce58e'
down_revision = '39c22cef0b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_strokes', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke_data', schema=None) as batch_op:
        batch_op.drop_column('_strokes')

    # ### end Alembic commands ###
