
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faSun,
  faMoon,
  faPencil,
  faBars,
  faPalette,
  faArrowRotateRight,
  faPenFancy,
  faGear,
  faSquare,
  faTrash,
  faFile,
  faMagnifyingGlass,
  faSitemap,
  faScissors,
  faDownload,
  faCloudArrowDown,
  faClipboard,
  faPen,
  faGrip,
  faClockRotateLeft,
  faCamera,
  faClipboardList,
  faVolumeHigh,
} from '@fortawesome/free-solid-svg-icons'

export {
  FontAwesomeIcon,
  faSun,
  faMoon,
  faPencil,
  faBars,
  faPalette,
  faArrowRotateRight,
  faPenFancy,
  faGear,
  faSquare,
  faTrash,
  faFile,
  faMagnifyingGlass,
  faSitemap,
  faScissors,
  faDownload,
  faCloudArrowDown,
  faClipboard,
  faPen,
  faGrip,
  faClockRotateLeft,
  faCamera,
  faClipboardList,
  faVolumeHigh,
}